version: '3'

services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.wisebits.local`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
    networks:
      - wisebits-network

  app:
    build: ./docker/php
    container_name: app
    expose:
      - "9000"
    volumes:
      - ./:/var/www/app
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - wisebits-network
    environment:
      PHP_IDE_CONFIG: "serverName=test.wisebits.local"

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./:/var/www/app/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - traefik
    networks:
      - wisebits-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test.rule=Host(`test.wisebits.local`)"
      - "traefik.http.routers.test.entrypoints=web"

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: wisebits
      POSTGRES_PASSWORD: wisebits
      POSTGRES_DB: wisebits
      PGDATA: /data/postgres/data
    volumes:
      - ./docker/pgdata:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - wisebits-network
    restart: unless-stopped

networks:
  wisebits-network: